alter table DVDEXCHANGE_TAKEN_ITEM add constraint FK_DVDEXCHANGE_TAKEN_ITEM_ON_DISK foreign key (DISK_ID) references DVDEXCHANGE_DISK(ID);
alter table DVDEXCHANGE_TAKEN_ITEM add constraint FK_DVDEXCHANGE_TAKEN_ITEM_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_DVDEXCHANGE_TAKEN_ITEM_ON_DISK on DVDEXCHANGE_TAKEN_ITEM (DISK_ID);
create index IDX_DVDEXCHANGE_TAKEN_ITEM_ON_USER on DVDEXCHANGE_TAKEN_ITEM (USER_ID);
